--- #YAML:1.0
name:                Abstract-Meta-Class
version:             0.13
author:
  - 'Adrian Witas <adrian@webapp.strefa.pl>'
abstract: Simple meta object protocol implementation.
license: perl
resources:
  license: http://dev.perl.org/licenses/
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:
    perl:                          5.6.1
    Carp:                          0
    Test::More:                    0
    Test::Pod:                     0
    Test::Pod::Coverage:           0
tests: t/* t/meta/*.t
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
